// This file is automatically generated. Do not modify it manually.
import {initializeApp, getApp, getApps} from 'firebase/app';

const firebaseConfig = {
  "projectId": "cargovaluator",
  "appId": "1:972849138960:web:3a9afda13bdf5752ff6995",
  "storageBucket": "cargovaluator.firebasestorage.app",
  "apiKey": "AIzaSyDpxBFkfaOyezhkI7FRh9iaR3NRjhOlrHU",
  "authDomain": "cargovaluator.firebaseapp.com",
  "messagingSenderId": "972849138960"
};
// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);

export {app};
