// This file is automatically generated. Do not modify it manually.
import {initializeApp, getApp, getApps} from 'firebase/app';

const firebaseConfig = {
  "apiKey": "AIzaSyC_iFXh_0PZkK_5c7s-58_Yh_Yko",
  "authDomain": "cargovaluate.firebaseapp.com",
  "projectId": "cargovaluate",
  "storageBucket": "cargovaluate.appspot.com",
  "messagingSenderId": "679054339458",
  "appId": "1:679054339458:web:4ff9a2886f499690184b25"
};
// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);

export {app};
