// This file is automatically generated. Do not modify it manually.
import {initializeApp, getApp, getApps} from 'firebase/app';

const firebaseConfig = {
  apiKey: "AIzaSyC_iFXh_0PZkK_5c7s-58_Yh_Yko",
  authDomain: "cargo-prx9x.firebaseapp.com",
  projectId: "cargo-prx9x",
  storageBucket: "cargo-prx9x.appspot.com",
  messagingSenderId: "972849138960",
  appId: "1:972849138960:web:3a9afda13bdf5752ff6995"
};
// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);

export {app};
